import type {Metadata} from "next";
import Header from "@/components/shared/header";
import {Providers} from "@/app/store/provaider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({children, modal}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <Providers>
            <main className="min-h-screen">
                <Header/>
                {children}
                {modal}
            </main>
        </Providers>
    );
}
